

services:
  backend:
    build: ./backend
    container_name: booking_backend
    network_mode: host
    env_file: ./backend/.env
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        VITE_MFU_AUTH_URL: ${VITE_MFU_AUTH_URL}
        VITE_CLIENT_ID: ${VITE_CLIENT_ID}
        VITE_REDIRECT_URI: ${VITE_REDIRECT_URI}
        VITE_SCOPE: ${VITE_SCOPE}
    container_name: booking_frontend
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
