

services:
  backend:
    build: ./backend
    container_name: booking_backend
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build: ./frontend
    container_name: booking_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
